
name: codecrafters-bittorrent
version: 0.1.0.0
license: BSD3

language: GHC2021

default-extensions:
  - DeriveGeneric
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

dependencies:
  - base >= 4.19 && < 5
  - fmt
  - mtl
  - optparse-applicative

library:
  source-dirs: src
  exposed-modules:
    - App
    - AppEnv
    - AppMonad
    - Bencode.Types
    - Bencode.Util
    - Messages.Extensions.Handshake
    - Messages.PeerHandshake
    - Options
    - Torrent.Hash
    - Torrent.Info
    - Torrent.MagnetLink
    - Torrent.PeerAddress
    - Util
  dependencies:
    - aeson
    - async
    - attoparsec
    - base16-bytestring
    - binary
    - bytesmith
    - bytestring
    - bytestring-encoding
    - containers
    - cryptohash-sha1
    - extra
    - formatting
    - http-client
    - http-types
    - ip
    - lens-family-core
    - modern-uri
    - network
    - network-simple
    - pipes
    - pipes-binary
    - pipes-bytestring
    - pipes-network
    - pipes-parse
    - primitive
    - random
    - req
    - safe
    - text
    - text-show
    - time
    - vector
    - word8

executables:
  codecrafters-bittorrent-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codecrafters-bittorrent
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
