
name: codecrafters-bittorrent
version: 0.1.0.0
license: BSD3

default-extensions:
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

dependencies:
  - base >= 4.19 && < 5
  - aeson # for JSON
  - network-simple # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - network # required when using bytestring
  - text # use Text rather than String
  - containers # may help with the database structure and debugging
  - time # may help with the expiry function
  - async # may help with concurrency
  - mtl # may help with structuring
  # Parsing libs
  - megaparsec
  - parser-combinators
  - parsec
  - attoparsec

executables:
  codecrafters-bittorrent-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
