
name: codecrafters-bittorrent
version: 0.1.0.0
license: BSD3

default-extensions:
  - DeriveGeneric
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

dependencies:
  - aeson
  - async
  - attoparsec
  - base >= 4.19 && < 5
  - base16-bytestring
  - binary
  - bytestring
  - bytestring-encoding
  - containers
  - cryptohash-sha1
  - fmt
  - formatting
  - http-client
  - http-types
  - ip
  - mtl
  - modern-uri
  - network
  - network-simple
  - optparse-applicative
  - random
  - req
  - split
  - text
  - text-show
  - time

library:
  source-dirs: src
  exposed-modules:
    - Bencode.Parser
    - Bencode.Types
    - Bencode.Util
    - Messages.PeerHandshake
    - Options
    - Torrent.Hash
    - Torrent.Info
    - Torrent.Peer
    - Util
  dependencies:
    - vector

executables:
  codecrafters-bittorrent-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codecrafters-bittorrent
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
