
name: codecrafters-bittorrent
version: 0.1.0.0
license: BSD3

default-extensions:
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - OverloadedRecordDot
  - OverloadedStrings
  - PartialTypeSignatures
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

dependencies:
  - aeson
  - async
  - attoparsec
  - base >= 4.19 && < 5
  - bytestring
  - containers
  - mtl
  - network
  - network-simple
  - text
  - time

library:
  source-dirs: src
  exposed-modules:
    - Bencode.Parser
    # - Server
    # - ServerEnv
    # - ServerM
  dependencies:
    - vector

executables:
  codecrafters-bittorrent-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codecrafters-bittorrent
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
